### ISSUE TITLE
Formatting changes '->' to '- >' in Laravel/jQuery 

### ISSUE THREAD

**Issue by thedoglett** [biati-digital/nova-php-cs-fixer#11]
**Describe the bug**
My Laravel installation includes blade templates to display success/errors in a toast. 

This formats fine in Visual Code, Sublime and Atom etc, however in Nova it changes from:

$errors->all()

to

$errors - > all()

Which gives an error of:

```
Facade\Ignition\Exceptions\ViewException
syntax error, unexpected '>' …
```

**Post an example code** - this is _before_ formatting on line 5 (message:)
```
@if($errors->any())
    <script>
    $(document).ready(function() {
        bulmaToast.toast({
            message: 'Validation error <br>' + @json(implode('<br>', $errors->all())),
            type: 'is-danger',
            dismissible: true,
            'duration': 6000,
            'position': 'top-right',
            'single': false,
            pauseOnHover: true,
            animate: {
                in: 'bounceIn',
                out: 'bounceOutUp'
            },
        });
    }); /* End document ready */
    </script>
@endif
```

**Post an example code** - this is _after_ formatting on line 5 (message:)
```
@if($errors->any())
    <script>
    $(document).ready(function() {
        bulmaToast.toast({
            message: 'Validation error <br>' + @json(implode('<br>', $errors - > all())),
            type: 'is-danger',
            dismissible: true,
            'duration': 6000,
            'position': 'top-right',
            'single': false,
            pauseOnHover: true,
            animate: {
                in: 'bounceIn',
                out: 'bounceOutUp'
            },
        });
    }); /* End document ready */
    </script>
@endif
```

**Expected behavior**
Formatting should not add these spaces in.

If I'm missing a setting, please point me in the right direction!

**Comment by biati-digital** [comment]
Hi, do you have enabled "Apply additional fixes"?

![CleanShot 2021-02-22 at 12 29 58](https://user-images.githubusercontent.com/1219228/108752959-bd899d00-7509-11eb-8f93-d4c29fa98c82.png)

Try it and let me know if it works for you, I'll submit an update soon that improves the formatting of PHP inside script tags

**Comment by thedoglett** [comment]
Hi, yes I did try that but it didn't make any difference.

Thanks for making the add on!

**Comment by biati-digital** [comment]
Are you using the latest version "2.0.5"?

**Comment by thedoglett** [comment]
Yep, just checked and it's 2.0.5.

**Comment by biati-digital** [comment]
Don't worry, I've checked your code in the update I'm working and it's formatted correctly. I'll try to have it ready by tomorrow.

**Comment by thedoglett** [comment]
Ah great stuff, thanks so much!

**Comment by thedoglett** [comment]
@biati-digital - just so you know, in Nova this extension didn't auto update. 

This morning (08/03/21) I realised it was stil 2.0.5 and it wasn't showing as having an update available. I manually download it from this repository to my machine and double clicked the extension for it to install/update.

Not sure if there's a delay between you releasing an update and it appearing in Nova, but just thought I'd let you know.

Thanks again.

**Comment by thedoglett** [comment]
@biati-digital Just wanted to let you know that the problem with -> turning to - > persists with version 2.0.6.

This…

![Screenshot 2021-03-09 at 14 54 06](https://user-images.githubusercontent.com/40393456/110489899-accf4e80-80e7-11eb-891c-80866fa32cb7.jpg)

Changes to this…

![Screenshot 2021-03-09 at 14 54 19](https://user-images.githubusercontent.com/40393456/110489913-ae991200-80e7-11eb-891a-ff6e70cdbc93.jpg)

This is what my settings are, plus the other extensions I have active…

![Screenshot 2021-03-09 at 14 54 47](https://user-images.githubusercontent.com/40393456/110490047-d38d8500-80e7-11eb-8411-699643c18beb.jpg)

I have turned off other extensions and it still happens (both using a shortcut and using the menu item), so doesn't seem to be conflict related.

**Comment by biati-digital** [comment]
H @thedoglett not sure how you have the 2.0.6 update, it has not been released yet and was not submitted to the extensions gallery, the latest version i can see in Nova is 2.0.5 and it shows no updates.

Anyway, 2.0.6 it's still in progress, i'm having a lot of work so i hope to have some free time soon.

**Comment by thedoglett** [comment]
I thought my version of nova wasn’t updating so I downloaded it from here...

![6E3C1A4C-085F-4002-BD8A-8D571AC51DA1](https://user-images.githubusercontent.com/40393456/110545161-9a273a80-8124-11eb-97e8-073fbf106c71.jpeg)

Sorry for the confusion, will wait for the update to show in Nova!

**Comment by biati-digital** [comment]
Ohh i see, no problem, i'll publish an update as soon as i can, i think for now you are better of using the version in the extensions library, 2.0.6 it's not ready yet.

**Comment by thedoglett** [comment]
Will do, cheers!

**Comment by biati-digital** [comment]
Hi, I've just submitted an update, the extension changed a lot so that's why the new version is 3.0.0, see all the changes here [CHANGELOG.md](https://github.com/biati-digital/nova-php-cs-fixer/blob/main/phpcsfixer.novaextension/CHANGELOG.md)

Please try it and let me know if it works.

**Comment by thedoglett** [comment]
Hi there, gave it a try and the -> issue is now resolved!

Thank you very much!

**Comment by biati-digital** [comment]
Perfect, I'll close this issue now.

**Comment by thedoglett** [comment]
Hi there, me again (long time no speak).

I'm working in Nova again (I gave up at one point and went back to Atom) but weirdly I have the same issue happening again. I'm using Nova v9.3 and 4.2.1 of PHP CS Fixer.

All of my addons have been deactivated apart from PHP CS Fixer and I've taken the following screenshots to show you the problem. As you can see, using curly braces for Laravel is fine in the two instances which have a green square around them, however in a script the braces and their content get pulled apart (indicated by the red box). This doesn't happen outside of the script.

BEFORE FORMATTING

![Screenshot 2022-06-08 at 16 46 27](https://user-images.githubusercontent.com/40393456/172661742-5ad49a70-3450-4f67-b7a7-cfe50bae7cf8.jpg)


AFTER FORMATTING

![Screenshot 2022-06-08 at 16 46 44](https://user-images.githubusercontent.com/40393456/172661787-205d6031-3c65-475f-ad53-bfa7682091fa.jpg)

I tend to use @json($variable->here) in scripts (which works fine) but a job I inherited uses {{$variable->here}} so if I inadvertently hit format everything could break.

These are the plugins I have active:

![Screenshot 2022-06-08 at 16 48 35](https://user-images.githubusercontent.com/40393456/172662169-4305ec8a-d5f8-43cd-a078-13625fde7089.jpg)

And these are the settings I have activated in the plugin.

![Screenshot 2022-06-08 at 16 44 32](https://user-images.githubusercontent.com/40393456/172662342-baa3440e-ac03-44a7-94bc-3539502e3a24.jpg)
![Screenshot 2022-06-08 at 16 44 49](https://user-images.githubusercontent.com/40393456/172662356-3be677f2-cc5a-40e5-b4f9-2c0529f09c54.jpg)


Have I missed a setting or is this a new bug?

Thanks in advance for your help!

**Comment by biati-digital** [comment]
Hi @thedoglett, good to hear from you.

`I'm working in Nova again (I gave up at one point and went back to Atom)`
I'm not surprised to hear that, seems that a lot of people gave up on Nova including me (I use PHP Storm). Are you trying Nova again because Atom will be archived?

I do not use Nova as my main editor but I do plan to keep updating the extensions we created so don't worry about that. I'll take a look at this probably in two weeks as I've a lot of work right now.

**Comment by thedoglett** [comment]
Hi, I’ve been using Nova so I can work directly on a server (some of the sftp plugins for Atom just wouldn’t work properly). Novas language autocompletes for Laravel are lacking but the remote editing works flawlessly so that’s why I’ve gone back.

I have tried PHP Storm but it seems sluggish compared to Atom (which I didn’t know was being archived). Visual Code also seems sluggish, but Sublime Text is really snappy so I may end up going back to that eventually if Atom stops working and Nova drives me mad.

Appreciate you taking a look at this, if the formatting works properly I’ll be confident using Nova on legacy systems and I’ll use Alfred to create snippets which I can call up with key commands until someone creates decent autocompletes.

Cheers again, and thanks for the heads up about Atoms archiving.

**Comment by biati-digital** [comment]
Hi @thedoglett sorry, for now I've no idea when I'll have the time to take a look at this. I've several client projects that I need to finish first, probably in 4/6 weeks.

**Comment by thedoglett** [comment]
Ah okay, just thought I'd check.

Many thanks.

**Comment by biati-digital** [comment]
Hi, i've published an update 4.4.2 that should fix this problem, please try it and let me know if it's working for you

**Comment by thedoglett** [comment]
Hi, the version in Nova is 4.2.2, not 4.4.2 - does it take some time for it to go live?

I did try the 4.2.2 version and the problem persists:

Before:
![Screenshot 2022-07-24 at 15 12 45](https://user-images.githubusercontent.com/40393456/180651148-52816f13-8127-4f5c-ac6f-e228cf3f38ff.jpg)
After:
![Screenshot 2022-07-24 at 15 12 35](https://user-images.githubusercontent.com/40393456/180651159-835186eb-400e-446f-9090-299a2ebac536.jpg)

If that's because 4.4.2 hasn't rolled out yet I'll check again and let you know if its fixed.

**Comment by thedoglett** [comment]
Update - it now leaves the curly braces alone, but its inserting 'ignore beautify' comments which are breaking the code. An example is below:

![Screenshot 2022-07-24 at 15 36 49](https://user-images.githubusercontent.com/40393456/180652183-4a6e9359-eb53-4f65-83f6-313fd18fbe79.jpg)

![Screenshot 2022-07-24 at 15 37 09](https://user-images.githubusercontent.com/40393456/180652169-21671153-b847-4854-9fb1-6eccd707b9de.jpg)

This is the extensions active when I tested it:
![Screenshot 2022-07-24 at 15 39 02](https://user-images.githubusercontent.com/40393456/180652224-ec51ab10-62be-4e57-b1ef-52e7da3c76c2.jpg)

If its not one thing, its another!

**Comment by biati-digital** [comment]
Hi, can you please paste the code here so I can copy/paste and make some tests?

**Comment by thedoglett** [comment]
Its a strange one, this, but I think I've worked out what's causing it.

Try formatting this in a blade.php file:

```
@section('upper_scripts')
<script src="{{ asset('js/dropzone.min.js') }}"></script>
@endsection

@section('upper_css')
<link rel="stylesheet" href="{{ asset('css/dropzone.min.css') }}" type="text/css"
/>
@endsection

<x-app-layout>
<x-slot name="header">
<div class="flex flex-wrap mx-auto w-full">
<div class="w-full md:w-1/2">
<h2 class="font-semibold text-xl text-gray-800 leading-tight">
{{ __('Media management') }}
</h2>
</div>
<div class="w-full md:w-1/2 sm:text-left mt-4 md:mt-0 md:text-right">
<a href="{{ url('/dashboard')}}" class="bg-gray-200 hover:bg-gray-300 transition px-4 py-2 rounded-lg text-gray-600 text-sm"><i class="fa fa-chevron-left mr-2"></i> Return to dashboard</a>
</div>
</div>
</x-slot>
```

You'll see that it formats fine.

Now, try this in the same file:

```
@section('upper_scripts')
<script src="{{ asset('js/dropzone.min.js') }}"></script>
@endsection

@section('upper_css')
<link rel="stylesheet" href="{{ asset('css/dropzone.min.css') }}" type="text/css"
/>
@endsection

<x-app-layout>
<x-slot name="header">
<div class="flex flex-wrap mx-auto w-full">
<div class="w-full md:w-1/2">
<h2 class="font-semibold text-xl text-gray-800 leading-tight">
{{ __('Media management') }}
</h2>
</div>
<div class="w-full md:w-1/2 sm:text-left mt-4 md:mt-0 md:text-right">
<a href="{{ url('/dashboard')}}" class="bg-gray-200 hover:bg-gray-300 transition px-4 py-2 rounded-lg text-gray-600 text-sm"><i class="fa fa-chevron-left mr-2"></i> Return to dashboard</a>
</div>
</div>
</x-slot>

<script>
alert('Test');
</script>
```

You'll see it gets the beautify comments at two points - the CSS file link and the return to dashboard a tag. 

The only difference in those two blocks of code is that further down the page (on the lower block) is another script tag. 

If you have one script tag its okay, add another and it breaks. Interestingly, if you move the script from the bottom so that its at the top (before the x-app-layout content) it formats fine again. Move it further down the page and it breaks.

Hope this helps…!

**Comment by biati-digital** [comment]
Hi, please try the new update 4.2.3 and let me know if it's working correctly.

**Comment by thedoglett** [comment]
That seems to have solved it (thanks!), but there's one more issue…

This is for a pagebuilder, and this is how my row code looks:

```
<div id="row-uuid-{{ $uniqueRowID }}" class="content-row-selector-off relative">
	<div class="{{ $row->classes }}"
		@isset($row_bg_image)
			style="background-image: url('{{ $row_bg_image }}')"
		@endisset data-div-type="row" data-div-element-type="row" data-div-state="off" data-is-editable="true" data-treat-row-as="{{ $row->treat_row_as ?? 'row' }}">
```
After formatting, it looks like this:
```
<div id="row-uuid-{{$uniqueRowID}}" class="content-row-selector-off relative">
	<div class="{{$row->classes}}" <blade isset|(%24row_bg_image)>
			style="background-image: url('{{$row_bg_image}}')"
	@endissetdata-div-type="row" data-div-element-type="row" data-div-state="off" data-is-editable="true" data-treat-row-as="{{$row->treat_row_as ?? 'row'}}">
```
So it looks like an issue with @isset.

Before I format the file, it outputs as this:

![Screenshot 2022-07-26 at 10 05 49](https://user-images.githubusercontent.com/40393456/180969444-ac6d89a8-6407-4e33-9871-4650d665f4c1.jpg)

But after it outputs as this:

![Screenshot 2022-07-26 at 09 56 24](https://user-images.githubusercontent.com/40393456/180966838-d8f49648-5e31-463c-9d3f-c9934ce6b5a0.jpg)

The result is that on the webpage you see this (rather than it being part of the code, its echoed onto the page):

![Screenshot 2022-07-26 at 10 02 53](https://user-images.githubusercontent.com/40393456/180968312-160d378d-2fe1-4851-aae9-95c2187de0da.jpg)

**Comment by biati-digital** [comment]
Hi, glad the other problem is solved, unfortunately this issue is a lot more complex, i run out of time and need to get back to work.  I can only recommend you to find an alternative to write that code as i wont be able to check this for some time.

**Comment by thedoglett** [comment]
Ah right, I understand. I’ll just use php tags for now until you can get around to looking at it. I really like Novas remote editing interface, PHP Storm is really sluggish and temperamental when I tried the trial so I’m prepared to wait.

Thanks for solving the script  issue though, at least I can start using it again.

👍

**Comment by biati-digital** [comment]
Hi, yeah PHP Storm can be a little difficult when you are starting, it took me like two weeks to configure it the way i like it because it has dozens and dozens of options, remote editing is nicer and easier in Nova, it's basically Transmit so that's expected.

Hopefully Nova gets better, soon they will release Nova 10 and will include Tree Sitter for parsing grammars which is really fast, the same used in Atom and NeoVim, it will be easier to port existing grammars (react, ocaml, ejs, erb, etc.) this way Nova will be able to correctly provide syntax highlighting for many languages.
